# This is a basic workflow to help you get started with Actions

name: release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with: 
        submodules: recursive

    - name: Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    
    # Runs a single command using the runners shell
    - name: make release tarball
      run: cd ..; mv denoise denoise-$version; tar cvf denoise-$version.tar; gzip denoise-$version.tar

    - name: get SHA
      id: shasum
      run: |
        echo ::set-output name=sha::"$(shasum -a 256 ./target/denoise-$version.tar.gz | awk '{printf $1}')"


